---
# vars/main.yml - OS-specific variables

# Debian/Ubuntu
docker_apt_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

docker_prereq_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
